# frozen_string_literal: true

module NinjaVanApi
  class WaybillResource < BaseResource
    # Retrieves a waybill for a given tracking number
    # @param tracking_number [String] The tracking number as generated by the Order API
    # @param hide_shipper_details [Boolean] A flag for hiding shipper's details
    # @param orientation [String] Specifies the orientation of the generated waybill ("portrait" or "landscape")
    # @return [Waybill] The waybill object
    def get(tracking_number, hide_shipper_details: nil, orientation: nil)
      params = { tid: tracking_number }
      params[:hide_shipper_details] = hide_shipper_details unless hide_shipper_details.nil?
      params[:orientation] = orientation if orientation

      response = get_request("2.0/reports/waybill", params: params)
      Waybill.new(response.body)
    end
  end
end
